apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  notes: "The configuration files reside in a git repo : https://github.com/armory/se-spinnaker-config"

resources:
- spinnakerservice.yml
#- spin-ingress.yml

patchesStrategicMerge:
- patch-componentsizing.yml # custom resource limits & requests
- patch-persistentStore.yml # gcs bucket
- patch-features.yml # UI Artifact Rewrite / Kustomize
- patch-github.yml # Github artifact provider
- patch-provider-k8s.yml #K8s provider
- patch-slack.yml # Slack
- patch-metrics.yml # Datadog
- patch-artifacts-gcs.yml # GCS artifacts
- patch-expose.yml #
- patch-auth.yml
- patch-endpoint.yml
- patch-profiles-gate.yml
#- patch-annotations.yml # Annotations for gate and deck services
- patch-dinghy.yml # pipelines as code
#- patch-security.yml
#- patch-provider-docker.yml
#- patch-opa.yml
#- patch-github.yml
#- patch-terraform.yml
#- patch-vault.yml
#- patch-logging.yml
#- patch-jenkins.yml

