apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      metricStores:
        enabled: true
        datadog:
          enabled: true
          api_key: encrypted:k8s!n:ts-poc-secrets!k:poc-spinnaker-datadog-api-key
          app_key: encrypted:k8s!n:ts-poc-secrets!k:poc-spinnaker-datadog-app-key