apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        authn:
          enabled: false
          oauth2:
            enabled: false
            client:
              clientId: encrypted:k8s!n:ts-poc-secrets!k:poc-spinnaker-authn-oauth2-clientid
              clientSecret: encrypted:k8s!n:ts-poc-secrets!k:poc-spinnaker-authn-oauth2-clientsecret
              accessTokenUri: https://github.com/login/oauth/access_token
              userAuthorizationUri: https://github.com/login/oauth/authorize
              scope: user:email
              #preEstablishedRedirectUri: https://spinnaker-gate.se.armory.io/login
              #useCurrentUri: false
            resource:
              userInfoUri: https://api.github.com/user
            userInfoMapping:
              email: email
              firstName: ''
              lastName: name
              username: login
            userInfoRequirements:
              company: '@teamsnap'
            provider: GITHUB
        authz:
          groupMembership:
            service: GITHUB
            google:
              roleProviderType: GOOGLE
            github:
              roleProviderType: GITHUB
              baseUrl: https://api.github.com
              accessToken: encrypted:k8s!n:ts-poc-secrets!k:poc-spinnaker-authn-authz-github-accessToken
              organization: teamsnap
            file:
              roleProviderType: FILE
            ldap:
              roleProviderType: LDAP
          enabled: false
   # profiles:
    #  gate:
    #    security:
    #      oauth2:
    #        providerRequirements:
    #          type: github
    #          organization: teamsnap